name: Build and Push to ECR
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}
      env:
        GOPATH: ${{ runner.workspace }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: aws-credentials-broker
      working-directory: ./src/github.com/${{ github.repository }}
      run: |
        VERSION=$(git describe --tags --always | sed -e 's/^v//g')
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION --build-arg VERSION=$(VERSION) .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION

    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
